apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: golang-simple-crud
  name: golang-simple-crud
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: golang-simple-crud
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: golang-simple-crud
    spec:
      containers:
        - env:
            - name: GIN_MODE
              value: debug
            - name: JWT_ISSUER
              value: golangSimpleCrud
            - name: JWT_SECRET_KEY
              value: verysecret12345
            - name: MONGODB_HOST
              value: mongo
            - name: MONGODB_PASSWORD
              value: example
            - name: MONGODB_USERNAME
              value: root
          image: golang_simple_crud:latest
          name: golang_simple_crud
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
